import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body className="bg-black text-white antialiased">
        {/* ดึง Navbar Component มาแสดงด้านบนสุด */}
        <Navbar />

        {/* เนื้อหาของแต่ละหน้า */}
        {children}
      </body>
    </html>
  );
}